# Generated by Django 4.1.7 on 2023-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Father_name', models.CharField(max_length=200)),
                ('DOB', models.DateTimeField()),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=6)),
                ('phone_num', models.IntegerField(max_length=10)),
                ('finger_print', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
