# Generated by Django 4.1.7 on 2023-03-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usregandlog', '0002_alter_register_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
