# Generated by Django 4.1.7 on 2023-03-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usregandlog', '0003_alter_register_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_num',
            field=models.CharField(max_length=10),
        ),
    ]
